In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [6]:
arr2.ndim  ## no of dimensions 

2

In [7]:
arr.ndim

1

In [8]:
arr2.shape ## rows & columns

(2, 5)

In [10]:
arr2.dtype ## data type

dtype('int32')

In [11]:
arr.dtype   

dtype('int32')

In [12]:
arr2.itemsize  ## only one item size 

4

In [13]:
arr2.nbytes    ## each item (4x10=20) 4 is item size

40

In [14]:
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [16]:
arr2[1,3]  ## (r,c)

4

In [19]:
arr2[0,:]   ## total row

array([1, 2, 3, 4, 5])

In [22]:
arr2[:,3]  ## total column

array([4, 4])

In [23]:
# Create a two-dimensional array
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr_2d.ndim

2

In [25]:
# Create a three-dimensional array
arr_3d = np.array([[[1, 2, 3],[4, 5, 6]],
                   [[7, 8, 9],[10, 11, 12]]])
arr_3d
arr_3d.ndim

3

In [27]:
# Create a four-dimensional array
arr_4d = np.array([[[[1, 2, 3],[4, 5, 6]],
                    [[7, 8, 9],[10, 11, 12]]],
                   [[[13, 14, 15],[16, 17, 18]],
                    [[19, 20, 21],[22, 23, 24]]]])
arr_4d.ndim

4

In [28]:
s=np.zeros((2,3))
s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
s1=np.ones((2,3))
s1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
s2=np.ones((2,3,4))
s2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [32]:
s3=np.full((2,3),98)
s3

array([[98, 98, 98],
       [98, 98, 98]])

In [35]:
s4 = np.random.rand(4,2)
s4

array([[0.50112999, 0.07542857],
       [0.62892471, 0.72021387],
       [0.84454838, 0.45648727],
       [0.41539462, 0.74121965]])

In [35]:
s4 = np.random.rand(4,2)
s4

array([[0.50112999, 0.07542857],
       [0.62892471, 0.72021387],
       [0.84454838, 0.45648727],
       [0.41539462, 0.74121965]])

In [36]:
s5 = np.identity(5)  ## identity matrix diagnosis same value
s5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
#### without copy method it's working like softcopy
a = np.array([1,2,3,4])
b = a
b[0]=12
a

array([12,  2,  3,  4])

In [41]:
## if your using copy method it's like hardcopy
a = np.array([1,2,3,4])
b = a.copy()
b[0]=12
a

array([1, 2, 3, 4])

In [42]:
a+2

array([3, 4, 5, 6])

In [43]:
a-2

array([-1,  0,  1,  2])

In [45]:
a*3

array([ 3,  6,  9, 12])

In [46]:
a**2

array([ 1,  4,  9, 16])