In [1]:
import numpy as np
print(np.__version__)

1.23.5


In [6]:
d0 = np.array(10)  ## 0D
print(d0) 
d1 = np.array([10,20,30]) ##1D
print(d1)

10
[10 20 30]


In [5]:
d2 = np.array([[10,20],[30,40]]) ## 2D
print(d2)

[[10 20]
 [30 40]]


In [7]:
d2[1][1]

40

In [8]:
d3 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(d3)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [10]:
d3[0][1][1]

40

In [11]:
## as array
a = [10,20,30]
b = np.asarray(a,dtype=float)
b

array([10., 20., 30.])

In [6]:
import numpy as np
c = [[10,20],[30,40]]
b = np.asarray(c,order="F")
for i in np.nditer(b):
    print(i)
print(b)

10
30
20
40


In [14]:
d = np.asarray(c,order="F")
for j in np.nditer(d):
    print(j)
print(d)

10
30
20
40
[[10 20]
 [30 40]]


In [19]:
k = b"Welcome to Numpy"
np.frombuffer(k,dtype="S1",count=9)

array([b'W', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't'], dtype='|S1')

In [20]:
k = b"Welcome to Numpy"
np.frombuffer(k,dtype="S1",offset=6)

array([b'e', b' ', b't', b'o', b' ', b'N', b'u', b'm', b'p', b'y'],
      dtype='|S1')

In [26]:
a = [10,20,30,40]
np.fromiter(a,dtype=int,count=3)

array([10, 20, 30])

In [30]:
n=np.eye(2)
print(n)

[[1. 0.]
 [0. 1.]]


In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
np.arange(1,100,20,dtype=float)

array([ 1., 21., 41., 61., 81.])

In [41]:
a = np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [46]:
np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [53]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [54]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [55]:
np.logspace(1,10,10,dtype=int)

array([         10,         100,        1000,       10000,      100000,
           1000000,    10000000,   100000000,  1000000000, -2147483648])

In [56]:
arr = [[1,2],[3,4]]
n = np.array(arr)
n

array([[1, 2],
       [3, 4]])

In [58]:
np.size(n)

4

In [59]:
np.shape(n)

(2, 2)

In [64]:
n.dtype

dtype('int32')

In [65]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a[0]

array([1, 2, 3])

In [67]:
a[0][1]

2

In [68]:
s = np.arange(10,100,10)
s

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
s[2:5]

array([30, 40, 50])

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
b = a.view()
b

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a[0][1]=100

In [73]:
b

array([[  1, 100,   3],
       [  4,   5,   6]])

In [74]:
a

array([[  1, 100,   3],
       [  4,   5,   6]])

In [76]:
a = np.array([40,30,80,4,3,2])
np.sort(a)

array([ 2,  3,  4, 30, 40, 80])

In [78]:
a= a.reshape(2,3)
a

array([[40, 30, 80],
       [ 4,  3,  2]])

In [79]:
np.sort(a,axis=0)

array([[ 4,  3,  2],
       [40, 30, 80]])

In [81]:
np.sort(a,axis=1)

array([[30, 40, 80],
       [ 2,  3,  4]])

In [82]:
marks = np.array([("ramu",95.0),("hari",90.8),("janu",72.5),("nani",99.8)],dtype=[("name","S1"),("Perc",float)])
marks

array([(b'r', 95. ), (b'h', 90.8), (b'j', 72.5), (b'n', 99.8)],
      dtype=[('name', 'S1'), ('Perc', '<f8')])

In [83]:
np.sort(marks,order="name")

array([(b'h', 90.8), (b'j', 72.5), (b'n', 99.8), (b'r', 95. )],
      dtype=[('name', 'S1'), ('Perc', '<f8')])

In [84]:
a= np.array([10,20,30])
b= np.array([40,50,60])
np.append(a,b)

array([10, 20, 30, 40, 50, 60])

In [85]:
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
np.append(a,b)

array([10, 20, 30, 40, 50, 60, 70, 80])

In [88]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [89]:
np.insert(a,3,35)

array([ 1,  2,  3, 35,  4])

In [91]:
np.insert(a,3,[35,45]).reshape(2,3)

array([[ 1,  2,  3],
       [35, 45,  4]])

In [93]:
np.delete(a,3)

array([1, 2, 3])

In [94]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[50, 60],
        [70, 80]]))

In [95]:
np.concatenate((a,b))

array([[ 1,  2],
       [ 3,  4],
       [50, 60],
       [70, 80]])

In [96]:
np.concatenate((a,b),axis=1)

array([[ 1,  2, 50, 60],
       [ 3,  4, 70, 80]])

In [98]:
arr= np.stack((a,b))
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[50, 60],
        [70, 80]]])

In [100]:
arr[0]

array([[1, 2],
       [3, 4]])

In [101]:
arr[1]

array([[50, 60],
       [70, 80]])

In [103]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [50, 60],
       [70, 80]])

In [104]:
np.dstack((a,b))

array([[[ 1, 50],
        [ 2, 60]],

       [[ 3, 70],
        [ 4, 80]]])

In [105]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[50, 60],
        [70, 80]]))

In [108]:
x = np.arange(1,100,10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [111]:
np.split(x,2)

[array([ 1, 11, 21, 31, 41]), array([51, 61, 71, 81, 91])]

In [112]:
np.split(x,5)

[array([ 1, 11]),
 array([21, 31]),
 array([41, 51]),
 array([61, 71]),
 array([81, 91])]

In [113]:
s1,s2,s3,s4,s5= np.split(x,5)

In [114]:
s1

array([ 1, 11])

In [115]:
s2

array([21, 31])

In [116]:
np.split(x,(4,3))

[array([ 1, 11, 21, 31]),
 array([], dtype=int32),
 array([31, 41, 51, 61, 71, 81, 91])]

In [117]:
a = np.arange(10,130,10).reshape(4,3)
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [118]:
np.where(a==80)

(array([2], dtype=int64), array([1], dtype=int64))

In [119]:
b = np.arange(10,130,10)
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [121]:
np.where(b==80)

(array([7], dtype=int64),)

In [124]:
np.where(a%20==0)

(array([0, 1, 1, 2, 3, 3], dtype=int64),
 array([1, 0, 2, 1, 0, 2], dtype=int64))

In [125]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [126]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [128]:
np.searchsorted(b,20)

1

In [129]:
np.searchsorted(b,[20,40])

array([1, 3], dtype=int64)

In [130]:
a,b

(array([[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120]))

In [133]:
a= np.array([[1,2],[3,4]])
b= np.array([[4,5],[6,7]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

In [134]:
np.add(a,b)

array([[ 5,  7],
       [ 9, 11]])

In [135]:
np.subtract(a,b)

array([[-3, -3],
       [-3, -3]])

In [136]:
np.multiply(a,b)

array([[ 4, 10],
       [18, 28]])

In [137]:
np.divide(a,b)

array([[0.25      , 0.4       ],
       [0.5       , 0.57142857]])

In [139]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [140]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [141]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

In [142]:
np.array_equal(a,b)

False

In [143]:
a==b

array([[False, False],
       [False, False]])

In [144]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

In [145]:
np.min(a)

1

In [146]:
np.min(a,axis=0)

array([1, 2])

In [147]:
np.min(a,axis=1)

array([1, 3])

In [148]:
np.sum(a)

10

In [149]:
np.mean(a)

2.5

In [150]:
np.median(a)

2.5

In [151]:
np.var(a)

1.25

In [152]:
np.std(a)

1.118033988749895